/// item_belongs_to_listOfItems(id)
var item = argument0;

if  (item.object_index != GENERAL_INSTRUCTIONS_FEE)
and (item.object_index != INSTRUCTIONS_FEE_ITEM)
and (item.object_index != GENERAL_INSTRUCTIONS_DETAILS)
and (item.object_index != INSTRUCTIONS_FEE_TOTAL)
and (item.object_index != lastPage_postageAndSundries)
and (item.object_index != lastPage_drawingCostsAndCopy)
and (item.object_index != lastPage_summonsToTax)
and (item.object_index != lastPage_stampThereon)
and (item.object_index != lastPage_attendingTaxation)
and (item.object_index != lastPage_injuriesBoardFee)
and (item.object_index != lastPage_WITNESSES)
and (item.object_index != WITNESS)
and (item.object_index != WITNESS_FEE)
and (item.object_index != lastPage_SUBTOTAL)
and (item.object_index != lastPage_ProVAT)
and (item.object_index != lastPage_OutlayToTotal)
and (item.object_index != lastPage_TOTAL)
and (item.object_index != lastPage_DatedSignature)
and (item.object_index != lastPage_CC_summonsToTax)
and (item.object_index != lastPage_CC_stampThereon)
and (item.object_index != lastPage_CC_attendingTaxation)
and (item.object_index != lastPage_CC_stampOnCertificate)
and (item.object_index != lastPage_Address)
and (item.object_index != lastPage_VATNumbers)
and (item.object_index != lastPage_VATNotRecoverable)
then return true;
else return false;
